### ISSUE TITLE
Allow alias to be deleted per user

### ISSUE THREAD

**Issue by abucodonosor** [awidegreen/vmail-rs#3]
Hello,

an alias can be added for more that one users,
but right now you can only delete the alias at random 
in such a case.

```
example:

team1.domain ->  user1.domain
team1.domain  -> user2.domain
team1.domain ->   user3.some.other.domain

```

Right now I cannot select which one should be deleted ,
or do I'm missing something ?

BR

**Comment by awidegreen** [comment]
Thanks for the issue! Unfortunately, you can't - I missed that use case. I'll fix it.
