### ISSUE TITLE
Support catchall aliases

### ISSUE THREAD

**Issue by fd0** [awidegreen/vmail-rs#4]
Thank you very much for your work! I'd love to be able to add (and remove) catchall aliases, where the `source_username` column is `NULL`. What's needed to add this? :)

Thanks!

**Comment by awidegreen** [comment]
I guess you are referring to [this](https://thomas-leister.de/mailserver-debian-stretch/#wie-kann-ich-mit-diesem-setup-catch-all-adressen-realisieren) note?

What about `%` to be a catch-all wildcard - in favor of `'*'` as this might interfere with shell globing if the quotes are omitted?!

```shell
# explicit catch-all
$ vmail-cli alias add % foo.com me bar.com
```

Remove would work the same way. 

```shell
$ vmail-cli alias remove % foo.com me bar.com
```

**Comment by fd0** [comment]
Exactly, that's what I configured. I also wrote back to Thomas (to thank him, mainly), adding a note that if users were to send email addresses not matching a specific alias or mailbox, the query in the `sender-login-maps.cf` needs to be changed as follows:

```sql
query = select concat(username, '@', domain) as 'owns' from accounts where username = '%u' AND domain = '%d' and en
abled = true union select concat(destination_username, '@', destination_domain) AS 'owns' from aliases where           
source_username = '%u' and source_domain = '%d' and enabled = true union select concat(destination_username, '@',      
destination_domain) AS 'owns' from aliases where source_username is null and source_domain = '%d' and enabled;         
```

I'm fine with using `%` or `*`, also the empty string (which would loosely resemble what's in the database) would work.

Thank you!

**Comment by awidegreen** [comment]
I added the feature in #5  - let me know if it's working for you.

**Comment by fd0** [comment]
Cool, thank you very much!
